//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DCFW.RC
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DCFW_DIALOG                 102
#define IDR_MAINFRAME                   128
#define IDD_BATCHSETUP                  130
#define IDD_FORMATCONVERTION            131
#define IDD_TCPROGRESS                  134
#define IDD_SCPROGRESS                  135
#define IDD_BUILDLIB                    138
#define IDC_ADDFILES                    1000
#define IDC_REMOVEFILES                 1001
#define IDC_FORMATCONVERSION            1002
#define IDC_BYTEREORDER                 1003
#define IDC_FILESTODO                   1005
#define IDC_COMBO2                      1009
#define IDC_BATCHSETUP                  1010
#define IDC_BUTTON1                     1011
#define IDC_ABOUT                       1011
#define IDC_DRAGDEFAULT                 1011
#define IDC_BROWSEFOROUTPUTNAME         1011
#define IDC_LIST1                       1012
#define IDC_BUTTON2                     1013
#define IDC_BUTTON3                     1014
#define IDC_REMOVEMISSING               1014
#define IDC_BROWSEFORSCRIPT             1014
#define IDC_LIST4                       1016
#define IDC_FILESINBATCH                1016
#define IDC_EDIT1                       1017
#define IDC_BUTTON5                     1018
#define IDC_REMOVEALL                   1018
#define IDC_BUTTON6                     1019
#define IDC_OPENBATCH                   1019
#define IDC_BUTTON7                     1020
#define IDC_DELETEBATCH                 1020
#define IDC_TEXT_PC                     1021
#define IDC_TEXT_AMIGA                  1022
#define IDC_TEXT_MAC                    1023
#define IDC_ITEMSIZE_BYTE               1027
#define IDC_ITEMSIZE_WORD               1028
#define IDC_ITEMSIZE_LONG               1029
#define IDC_ITEMS_PER_LINE              1034
#define IDC_LABEL_METHOD                1041
#define IDC_N_START                     1042
#define IDC_INC_N                       1044
#define IDC_DEC_N                       1045
#define IDC_LABEL_PREFIX                1046
#define IDC_LABEL_SUFFIX                1047
#define IDC_N_FORMAT                    1048
#define IDC_CHECK1                      1049
#define IDC_TEXT_MODE                   1050
#define IDC_SOURCE_MODE                 1051
#define IDC_OUTPUT_AS                   1052
#define IDC_RADIX                       1053
#define IDC_SAVEASSTRINGS               1054
#define IDC_RADIO1                      1055
#define IDC_SAVEBATCH                   1056
#define IDC_IMPORTTEXTFILE              1057
#define IDC_SAVEASBAT                   1058
#define IDC_BUILDLIBRARY                1059
#define IDC_EXTRACTPORTION              1060
#define IDC_CHECKCELS                   1060
#define IDC_TCCURRENTFILE               1064
#define IDC_TCSOURCETYPE                1065
#define IDC_TCSTATUS                    1066
#define IDC_BYTEORDER                   1069
#define IDC_BOMOTOROLA                  1070
#define IDC_SCFILE                      1071
#define IDC_SCLINE                      1072
#define IDC_OUTPUTNAME                  1073
#define IDC_SWAPSRCWORDS                1078
#define IDC_SWAPSRCDWORDS               1079
#define IDC_MASKINT                     1082
#define IDC_MASKAFTERDATA               1083
#define IDC_WORDMASK                    1084
#define IDC_DWORDMASKS                  1085
#define IDC_NOTABLE                     1086
#define IDC_USEWORDINDEX                1088
#define IDC_INCLUDEFILESIZE             1089
#define IDC_INCNUMENTRIES               1090
#define IDC_DATAALIGNMENT               1091
#define IDC_SCRIPTFILENAME              1093
#define IDC_WRITETOLOG                  1094
#define IDC_USEFILESINBATCH             1095
#define IDC_USESCRIPT                   1096

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1097
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
